
version: 2

models:
  #- name: my_first_dbt_model
  #  description: "A starter dbt model"
  #  columns:
  #    - name: id
  #      description: "The primary key for this table"
  #      data_tests:
  #        - unique
  #        - not_null
#
  #- name: my_second_dbt_model
  #  description: "A starter dbt model"
  #  columns:
  #    - name: id
  #      description: "The primary key for this table"
  #      data_tests:
  #        - unique
  #        - not_null

  - name: int_vbrp
    description: "full view of table konv"

  - name: int_vbap
    description: "full view of table makt"

  - name: int_vbak
    description: "full view of table konv"

  - name: int_konv
    description: "full view of table makt"
