
version: 2

sources:

  - name: raw
    #prod is airbyte output in eltl-pipeline VM
    #dev is personal VM
    schema: |
      {%- if target.name == "dev" -%} multi_pipeline
      {%- elif target.name == "prod" -%} staging
      {%- else -%} invalid_target
      {%- endif -%}
    tables:
      - name: KONV
      - name: VBRP
      - name: VBAP
      - name: VBAK
      - name: VBRK
      - name: LIPS
      - name: KNA1
      - name: MARD
      - name: EKPO
      - name: MARA
