version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webserver:
    image: apache/airflow:2.6.0
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__CORE__FERNET_KEY: 'YOUR_RANDOM_FERNET_KEY'
      AIRFLOW__WEBSERVER__WORKERS: 2
      # BigQuery credentials (set the path to your credentials file here)
      GOOGLE_APPLICATION_CREDENTIALS: "/opt/airflow/bigquery_key.json"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./bigquery_key.json:/opt/airflow/bigquery_key.json  # Mount the credentials
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    image: apache/airflow:2.6.0
    depends_on:
      - webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: 'YOUR_RANDOM_FERNET_KEY'
      GOOGLE_APPLICATION_CREDENTIALS: "/opt/airflow/bigquery_key.json"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./bigquery_key.json:/opt/airflow/bigquery_key.json  # Mount the credentials
    command: scheduler

volumes:
  postgres_data:
